### ISSUE TITLE
2 Server Functions for Authentication

### ISSUE THREAD

**Issue by 0xSero** [Raid-Guild-Season-VI-Keyp-Integration/keyp-minetest-auth-ui#3]
Server will have to store session token for user logins, and generate a 6 digit auth code:

    Store session token and generate 6 character Auth string (Maybe use auth: session token mapping?)
    Listen for http calls: accepts 6 char string, match with auth-code: session-token
        If match return session token and user public address
        If no match handle error
        
   This will be a rest API with 2 end points:
   
   1. takes a session token as a parameter, stores the token and generates a 6 character auth token then returns the auth token as a response
   
   2. Takes a 6 character auth token as a paramter and returns a session token if a match is found.
   
   Follow the nextjs docs to build this out:
   https://nextjs.org/docs/pages/building-your-application/routing/api-routes

**Comment by 0xSero** [comment]
Is this enough detail @xxavier-dev or do you need more info?

**Comment by xxavier-dev** [comment]
A little more info would be helpful - I'm kind of a noob with this domain/tech stack.

**Comment by 0xSero** [comment]
> A little more info would be helpful - I'm kind of a noob with this domain/tech stack.

I'll write a more detailed spec by end of day.

**Comment by 0xSero** [comment]
Updated with more info @xxavier-dev if this still isn't enough info we can pair program oon it

**Comment by xxavier-dev** [comment]
Thanks for the info @Seroxdesign ! If you're available I would get a lot of value if we could set some time to help me set up my dev environment and hand-holding a little bit during this first part of the project. Most of my dev experience has been with internal tooling and cloud-based automation so this is still a little foreign to me. I'm in the process of switching industries/domains (out of semiconductors) so some extra help right now would go a long way if you could offer it
